spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:bancowdemoDb
    driver-class-name: org.h2.Driver
    username: root
    password: '1111'

  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: false

    properties:
      format-sql: true
      hibernate:
        show-sql: true
        format_sql: true

